---
title: "Motor Trend Cars"
output: html_document

---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

```

## Data

This data is from Motor Trend magazine in 1974. It presents data for 32 automobiles regarding performance (miles per gallon, gross horsepower, and 1/4 mile time) and design (cylinders, gears, carburetors, axle ratio, weight, displacement, transmission and engine type).

Variables:

```{r summary mtcars, echo=FALSE}

names(mtcars)

```

``` {r labels, echo = FALSE}
# Labelling variables
var.labels = c(mpg="Miles per gallon", cyl="Number of cylinders", disp="Displacement", hp="Horsepower", drat="Axle ratio", wt="Weight", qsec="1/4 mile time", vs="V/S", am="Transmission", gear="Number of forward gears", carb="Number of carburetors")

label(mtcars) = lapply(names(var.labels), 
function(x) label(mtcars[,x]) = var.labels[x])

```


2. Exploring the variables
```{r descr, echo=FALSE}
stat.desc(mtcars$mpg, basic=FALSE) # summary stats for variables of interest, not very necessary if the summary function will give the whole outputs.

summary(mtcars)

```

## Plots
# Some boxplot distributions 
```{r am boxplots, echo=FALSE}

mtcars$am <- factor(mtcars$am,levels=c(0,1),
   labels=c("Automatic","Manual"))
qplot(mtcars$am, mtcars$mpg, geom = "boxplot", main = "MPG by Transmission Type", xlab = "Transmission", ylab = "MPG")
```

```{r boxplots}


boxplot(mtcars, las = 2, main="Boxplots of all variables", col=c("red", "sienna", "black", "blue", "royalblue", "yellow", "violet", "brown", "green", "palevioletred1", "darkgreen"))


# Boxplots of variables of interest
attach(mtcars)
par(mfrow=c(1,3)) 
boxplot(wt, col="blue", xlab="Weight")
boxplot(carb, col="yellow", xlab="Carburetors")
boxplot(hp, col="cyan", xlab="Horsepower")
title("Boxplots of variables of interest", outer=TRUE)

# Scatterplots of mpg (as DV) and other variables
attach(mtcars)
par(mfrow=c(1,3))
plot(wt,mpg, main="Weight vs. speed (mpg)")
plot(carb,mpg, main="Carburetors vs. speed (mpg)")
plot(hp, mpg, main="Horsepower vs. speed (mpg)")

# Histograms of chosen variables
attach (mtcars)
par(mfrow=c(1,3))
hist(wt, main=paste(var.labels["wt"]))
hist(carb, main=paste(var.labels["carb"]))
hist(hp, main=paste(var.labels["hp"]))

# Looped Histograms (does not work because am is not numeric)
#     variables<-names(mtcars)
#     for(i in variables)
#   {
#     colors = c("red", "yellow", "green", "violet", "orange", "blue", "pink", "cyan") 
#     dev.new()
#     xLabel <- paste(var.labels[i]) 
#     hist(mtcars[, i],
#     main=paste("Distribution of", xLabel),
#     xlab=xLabel)
#     
    #}

# All histograms (I can't really figure how to get different scales. I tried putting in the limit function, but it does not work here :())
ggplot(melt(mtcars),aes(x=value)) + geom_histogram() + facet_wrap(~variable)

```


